remote_theme: ddc-java/ddc-day

title: Codebreaker
description: A code-breaking solitaire puzzle game.

author:
  name: Cynthia Nikolai
  copyright: false
  email: cnikolai@earthlink.net

page_navigator:
  enabled: true

titles_from_headings:
  enabled: false

